#!/usr/bin/env python3
"""Render HBC's Droid fonts into anti-aliased glyph bitmaps for the overlay.

usage: python3 sdk/hbc_agent/mkfont.py   (writes sdk/hbc_agent/ov_font.h)

Needs Pillow (`pip install pillow` in .venv). The output is committed, so
building the agent does not need Python or the fonts.
"""

import pathlib

from PIL import Image, ImageDraw, ImageFont

root = pathlib.Path(__file__).resolve().parents[2]
DATA = root / "channel/channelapp/data"
OUT = pathlib.Path(__file__).with_name("ov_font.h")
FIRST, LAST = 32, 126

# (C name, file, pixel size)
FONTS = [("ov_font_regular", "droid.ttf", 14),
         ("ov_font_bold", "droidbold.ttf", 14),
         ("ov_font_title", "droidbold.ttf", 16)]


def render(name, file, size):
    font = ImageFont.truetype(str(DATA / file), size)
    ascent, descent = font.getmetrics()
    glyphs, bits = [], bytearray()
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        adv = round(font.getlength(ch))
        left, top, right, bottom = font.getbbox(ch)
        w, h = max(0, right - left), max(0, bottom - top)
        if w and h:
            img = Image.new("L", (w, h), 0)
            ImageDraw.Draw(img).text((-left, -top), ch, font=font, fill=255)
            data = img.tobytes()
        else:
            data = b""
        glyphs.append((w, h, left, top, adv, len(bits)))
        bits += data
    lines = [f"static const ov_glyph {name}_glyphs[{LAST - FIRST + 1}] = {{"]
    for code, (w, h, x, y, adv, off) in zip(range(FIRST, LAST + 1), glyphs):
        lines.append(f"\t{{{w}, {h}, {x}, {y}, {adv}, {off}}}, /* {chr(code)!r} */")
    lines.append("};")
    lines.append(f"static const uint8_t {name}_bits[{max(1, len(bits))}] = {{")
    for i in range(0, len(bits), 24):
        lines.append("\t" + ", ".join(str(b) for b in bits[i:i + 24]) + ",")
    lines.append("};")
    lines.append(f"static const ov_font {name} = {{ {name}_glyphs, {name}_bits, {ascent}, "
                 f"{ascent + descent} }};")
    return "\n".join(lines)


def main():
    parts = [
        "/* Generated by sdk/hbc_agent/mkfont.py from channel/channelapp/data/droid*.ttf",
        " * (Droid Sans, Apache License 2.0). Do not edit. */",
        "",
        "#ifndef OV_FONT_H",
        "#define OV_FONT_H",
        "",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "\tuint8_t w, h;      /* bitmap size */",
        "\tint8_t x, y;       /* bitmap offset from the pen, y from the line top */",
        "\tuint8_t adv;       /* pen advance */",
        "\tuint16_t off;      /* offset into the bits */",
        "} ov_glyph;",
        "",
        "typedef struct {",
        "\tconst ov_glyph *glyphs;   /* ASCII 32 to 126 */",
        "\tconst uint8_t *bits;      /* 8-bit coverage */",
        "\tint ascent, height;",
        "} ov_font;",
        "",
    ]
    for spec in FONTS:
        parts.append(render(*spec))
        parts.append("")
    parts.append("#endif")
    OUT.write_text("\n".join(parts) + "\n", newline="\n")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
