#!/usr/bin/env python3
"""Render HBC's Droid fonts into anti-aliased glyph bitmaps for the overlay,
and crop HBC's pointer (with its shadow) into an RGBA image.

usage: python3 sdk/hbc_agent/mkfont.py   (writes sdk/hbc_agent/ov_font.h)

Needs Pillow (`pip install pillow` in .venv). The output is committed, so
building the agent does not need Python or the fonts.
"""

import pathlib

from PIL import Image, ImageDraw, ImageFont

root = pathlib.Path(__file__).resolve().parents[2]
DATA = root / "channel/channelapp/data"
OUT = pathlib.Path(__file__).with_name("ov_font.h")
FIRST, LAST = 32, 126

# (C name, file, pixel size). Each also gets a "_wide" copy condensed to
# three quarters of its width: on a 16:9 TV the Wii stretches a 640-pixel
# picture sideways by a third, and the condensed copy undoes that.
FONTS = [("ov_font_regular", "droid.ttf", 14),
         ("ov_font_bold", "droidbold.ttf", 14),
         ("ov_font_title", "droidbold.ttf", 16)]
WIDE = 0.75


def squeeze(img, sx):
    """img condensed horizontally by sx, from a 4x supersample."""
    if sx == 1:
        return img
    w = max(1, round(img.width * sx))
    return img.resize((w * 4, img.height * 4), Image.LANCZOS).resize((w, img.height), Image.LANCZOS)


def render(name, file, size, sx=1):
    font = ImageFont.truetype(str(DATA / file), size)
    ascent, descent = font.getmetrics()
    glyphs, bits = [], bytearray()
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        adv = round(font.getlength(ch) * sx)
        left, top, right, bottom = font.getbbox(ch)
        w, h = max(0, right - left), max(0, bottom - top)
        if w and h:
            img = Image.new("L", (w, h), 0)
            ImageDraw.Draw(img).text((-left, -top), ch, font=font, fill=255)
            img = squeeze(img, sx)
            w = img.width
            data = img.tobytes()
        else:
            data = b""
        glyphs.append((w, h, round(left * sx), top, adv, len(bits)))
        bits += data
    lines = [f"static const ov_glyph {name}_glyphs[{LAST - FIRST + 1}] = {{"]
    for code, (w, h, x, y, adv, off) in zip(range(FIRST, LAST + 1), glyphs):
        lines.append(f"\t{{{w}, {h}, {x}, {y}, {adv}, {off}}}, /* {chr(code)!r} */")
    lines.append("};")
    lines.append(f"static const uint8_t {name}_bits[{max(1, len(bits))}] = {{")
    for i in range(0, len(bits), 24):
        lines.append("\t" + ", ".join(str(b) for b in bits[i:i + 24]) + ",")
    lines.append("};")
    lines.append(f"static const ov_font {name} = {{ {name}_glyphs, {name}_bits, {ascent}, "
                 f"{ascent + descent} }};")
    return "\n".join(lines)


TAB, NL = chr(9), chr(10)


def cursor(name):
    """HBC's pointer as HBC draws it (cursors.c): the grey shade 2 pixels
    right and 4 down, then the hand over it; hotspot at the image centre.
    The overlay rotates it with the remote and squeezes it on 16:9 itself."""
    pic = Image.open(DATA / "cursor_pic.png").convert("RGBA")
    shade = Image.open(DATA / "cursor_shade.png").convert("RGBA")
    img = Image.new("RGBA", (pic.width + 2, pic.height + 4), (0, 0, 0, 0))
    img.alpha_composite(shade, (2, 4))
    img.alpha_composite(pic, (0, 0))
    left, top, right, bottom = img.getbbox()
    crop = img.crop((left, top, right, bottom))
    hx, hy = pic.width // 2 - left, pic.height // 2 - top
    data = crop.tobytes()
    lines = [f"static const uint8_t {name}_rgba[{len(data)}] = {{"]
    for i in range(0, len(data), 24):
        lines.append(TAB + ", ".join(str(b) for b in data[i:i + 24]) + ",")
    lines.append("};")
    lines.append(f"static const ov_sprite {name} = {{ {name}_rgba, {crop.width}, {crop.height}, "
                 f"{hx}, {hy} }};")
    return NL.join(lines)


def main():
    parts = [
        "/* Generated by sdk/hbc_agent/mkfont.py from channel/channelapp/data: the",
        " * Droid fonts (Apache License 2.0) and HBC's pointer. Do not edit. Types",
        " * are in ov_draw.h; only ov_draw.c includes this. */",
        "",
    ]
    for name, file, size in FONTS:
        parts.append(render(name, file, size))
        parts.append(render(name + "_wide", file, size, WIDE))
        parts.append("")
    parts.append("/* HBC's pointer: channel/channelapp/data/cursor_pic.png over cursor_shade.png. */")
    parts.append(cursor("ov_cursor"))
    parts.append("")
    OUT.write_text("\n".join(parts) + "\n", newline="\n")
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
